# Generated by Django 5.0.4 on 2024-04-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0003_rename_situação_produto_vendas_situacao_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendas",
            name="cpf_cliente",
            field=models.CharField(max_length=11, verbose_name="CPF do Cliente"),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="situacao_produto",
            field=models.IntegerField(default=1, verbose_name="Situação"),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="telefone_cliente",
            field=models.CharField(max_length=11, verbose_name="Telefone do Cliente"),
        ),
    ]
